#!/bin/sh

### BEGIN INIT INFO
# Provides:		ntvld
# Required-Start:	$remote_fs $syslog	<=?
# Required-Stop:	$remote_fs $syslog	<=?
# Default-Start:	2 3 4 5				<=?
# Default-Stop:							<=?
# Short-Description:	Linux ntvl server
### END INIT INFO

# /etc/init.d/ntvl: starts and stops the ntvl daemon(s)

set -e 	# Exit immediately if a simple command exits

test -x /usr/sbin/ntvld || exit 0

# START
	# TODO: Log start message
	# TODO: call ntvld start

# STOP
	# TODO: Log stop message
	# TODO: call ntvld stop

# RESTART
	# TODO: Log restart message
	# TODO: Call STOP
	# TODO: Call START

# STATUS
	# TODO: call ntvld status
	
# USAGE (evrething else)
	# TODO: show "Usage: /etc/init.d/ntvl {start|stop|restart|status}" || true

exit 0
